<?php

// This file was generated by running "composer dump-env prod"

return array (
  'APP_ENV' => 'prod',
  'APP_SECRET' => 'ZDY4MTgwZTEzMjVjZDE5NjhhYjAyODI1',
  'DATABASE_URL' => 'mysql://apiuser:apiuser@mariadb:3306/api?serverVersion=mariadb-10.4.19',
  'JWT_SECRET_KEY' => 'MGJhNTVjOTU1Mzg3ZTg4ODRlMjNjNGQ2',
  'CORS_ALLOW_ORIGIN' => '^https?://(localhost|127\\.0\\.0\\.1)(:[0-9]+)?$',
);