<?php

// This file was generated by running "composer dump-env prod"

return array(
	'APP_ENV' => 'dev',
	'APP_SECRET' => 'ZDY4MTgwZTEzMjVjZDE5NjhhYjAyODI1',
	'DATABASE_URL' => 'mysql://root:toor@localhost:3306/db',
	// 'DATABASE_URL' => 'postgresql://postgres:password@db:5432/db?serverVersion=13&charset=utf8',
	'JWT_SECRET_KEY' => 'MGJhNTVjOTU1Mzg3ZTg4ODRlMjNjNGQ2',
	'JWT_PASSPHRASE' => 'fdfg546dfg4dfgdf65sg4df5gfdgf32gfd13gF1DG3DF',
	'CORS_ALLOW_ORIGIN' => '^https?:\\/\\/(localhost|127\\.0\\.0\\.1)(:[0-9]+)?$',
	'MAILER_DSN' => 'smtp://cb4f1cc59099d9:a62cf345361dba@smtp.mailtrap.io:2525?encryption=tls&auth_mode=login',
	// 'MAILER_DSN' => 'sendinblue+api://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@default',
	'APP_NAME' => 'BeSpectacled',
	'APP_MAIL' => 'contact@bespectacled.com',
	// 'APP_MAIL' => 'nstudio2k@gmail.com',
	'CHOKIDAR_USEPOLLING' => true,
	'WATCHPACK_POLLING' => true
);